/// Every `#[tauri::command]` registered in `generate_handler!` (`src/lib.rs`).
///
/// Naming them here is the whole reason the capability files bind at all.
/// `tauri-2.11.5` only runs an app command through the ACL when
/// `plugin_command.is_some() || has_app_acl_manifest || !is_local`
/// (`src/webview/mod.rs:1823`). Both Butterfly Speak windows load local URLs and
/// there was no app manifest, so until this list existed *every* command below
/// was invokable from the overlay — a transparent, click-through pill — with
/// nothing in `capabilities/` mentioning it.
///
/// `AppManifest::commands` writes an `allow-<command>`/`deny-<command>` pair per
/// entry into `permissions/autogenerated/` (`tauri-build-2.6.3/src/acl.rs:278`,
/// `tauri-utils-2.9.3/src/acl/build.rs:255`), and the app manifest that produces
/// is what flips `has_app_acl_manifest` (`tauri-build-2.6.3/src/acl.rs:408`).
/// That switch is all-or-nothing and app-wide: the moment one app permission
/// exists, every command is deny-by-default in *both* windows. So this list and
/// `capabilities/main.json` have to be added to together — a command registered
/// in `generate_handler!` but missing from either one is silently rejected at
/// runtime with "not allowed by ACL", not a compile error. The `capability_split`
/// tests in `src/lib.rs` are what turn that into a compile-time-ish failure.
///
/// The generated files are build output, not source: `.gitignore` keeps
/// `permissions/autogenerated/` out of the tree so this list stays the only
/// place the set is written down.
const COMMANDS: &[&str] = &[
    "get_settings",
    "set_settings",
    "list_models",
    "polish_status",
    "download_model",
    "cancel_download",
    "delete_model",
    "select_model",
    "list_mics",
    "system_info",
    "set_meter",
    "hotkey_capture",
    "ensure_support_models",
    "sarvam_key_status",
    "set_sarvam_key",
    "validate_sarvam_key",
    "custom_endpoint_key_status",
    "set_custom_endpoint_key",
    "check_custom_endpoint",
    "prompt_defaults",
    "preview_prompt",
    "test_prompt",
    "endpoint_test_connection",
    "endpoint_list_models",
    "history_list",
    "history_search",
    "history_delete",
    "history_update_text",
    "history_clear",
    "create_note",
    "get_note",
    "update_note",
    "delete_note",
    "list_notes",
    "search_notes",
    "list_folders",
    "create_folder",
    "rename_folder",
    "delete_folder",
    "list_note_actions",
    "create_note_action",
    "update_note_action",
    "delete_note_action",
    "run_note_action",
    "generate_note_title",
    "export_settings",
    "import_settings",
    "undo_learned_correction",
    "export_note",
    "pick_notes_mirror_dir",
    "rebuild_notes_mirror",
    "persist_resolved_theme",
    "import_pick_files",
    "import_start",
    "import_cancel",
    "import_clear",
    "import_status",
    "update_status",
    "update_check",
    "update_install",
    "cloud_sign_in",
    "cloud_sign_out",
    "cloud_status",
    "cloud_usage",
    "cloud_delete_account",
];

/// Delete `permissions/autogenerated/*.toml` for commands that are no longer in
/// `COMMANDS`.
///
/// `autogenerate_command_permissions` only ever writes
/// (`tauri-utils-2.9.3/src/acl/build.rs:307`); nothing removes the file for a
/// command that has since been renamed or deleted. The directory is gitignored
/// build output, so a branch switch does not clean it either, and
/// `app_manifest_permissions` then re-reads the whole of `permissions/**/*`
/// (`tauri-build-2.6.3/src/acl.rs:315-328`). The result is that a deleted
/// command's `allow-<gone>` survives on disk and stays a valid, grantable
/// permission — `validate_capabilities` keeps passing for a capability naming a
/// command the app no longer has. That is precisely the drift `capability_split`
/// exists to catch, and it is the one direction those tests cannot see, because
/// they read the three source files and never the generated set.
///
/// Only strays are removed, never rewritten: `write_if_changed` leaves current
/// files untouched, so in the ordinary case this touches nothing and the
/// `cargo:rerun-if-changed=permissions` instruction does not fire a rebuild.
fn prune_stale_permissions() {
    let dir = std::path::Path::new("permissions/autogenerated");
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let current = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .is_some_and(|stem| COMMANDS.contains(&stem));
        if !current {
            println!(
                "cargo:warning=removing stale app permission {} (no such command)",
                path.display()
            );
            let _ = std::fs::remove_file(&path);
        }
    }
}

fn main() {
    prune_stale_permissions();
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("tauri-build failed");
}
