#!/usr/bin/env python3
"""fetch_corpora.py -- downloads, converts, and samples the formatting-eval
corpus fixtures committed under tests/fixtures/*.jsonl.

Methodology (AssemblyAI's Universal-2-TF, arXiv:2501.05948): take text that
ALREADY has correct punctuation and casing, strip it to lowercase and
unpunctuated to simulate raw ASR output, then measure how well the
formatter restores it. No individual's writing preferences enter this --
every fixture line is `input` (simulated raw ASR) paired with `target`
(the ground truth it should restore to), one JSON object per line:

    {"id":..., "source":..., "kind":"punctuation"|"disfluency", "lang":...,
     "input":..., "target":..., "verbatim": optional, "tags": optional}

Run it from the repo root with no arguments. It needs only the Python 3
standard library: every source fetched below is JSON or pipe-delimited text.

    python tools/fetch_corpora.py

It downloads each source's real upstream data (full sets -- that IS the "on
demand" fetch), converts it to the fixture schema above, deterministically
samples ~200 cases per source (SAMPLE_SEED below, so re-running reproduces
the same commit-sized sample), and writes:

    tests/fixtures/<source>.jsonl   -- one file per source, ~200 lines
    tests/fixtures/LICENSE.md       -- generated attribution block, for humans
    tests/fixtures/sources.json     -- the same metadata, for the harness

Raw downloads are cached under tools/.cache/ (gitignored) so re-runs don't
re-fetch multi-megabyte archives.

------------------------------------------------------------------------
WHAT GETS WRITTEN UNDER tests/fixtures/, AND WHAT GATES IT
------------------------------------------------------------------------
Three functions write under `tests/fixtures/`, and only one of them writes
corpus DATA:

  * `write_fixture()` -- the only writer of `*.jsonl` case data. It refuses
    (raises, writes nothing) unless the `source_key` is a key of `SOURCES`
    below AND the license recorded for it is in `ALLOWED_LICENSES`. There
    is no argument, flag, or environment variable that bypasses either
    check.
  * `write_license_md()` and `write_sources_json()` -- generated metadata.
    Neither writes case data; both just serialize the `SOURCES` table, so
    neither can introduce a source `write_fixture` would have refused.

THE GATE IS ON THE LICENSE, NOT ON THE KEY. Adding a row to `SOURCES` is
not by itself permission to ship it: `ALLOWED_LICENSES` is the whitelist,
and a source carrying anything else -- CC BY-NC, CC BY-ND, an LDC
agreement, no license at all -- is refused at import time and again at
write time, however impeccable its key looks. This is deliberate: the
failure mode being defended against is a contributor adding a
well-described non-commercial source and everything downstream quietly
recording "CC BY-NC 4.0" as though that were fine.

Every source actually committed here was license-verified against a
FIRST-PARTY statement found at fetch time (a LICENSE file shipped in the
source's own distribution, or a `license` field in its own dataset card),
not merely trusted from whatever named it. See `PENDING_SOURCES` and
`BLOCKED_SOURCES` below for sources that were investigated and are
DELIBERATELY not in `SOURCES`, and why -- DISCO is named as CC BY 4.0, but
that verification step turned up no license grant for its data.
`tests/fixtures/LICENSE.md` (generated by this script) repeats all of this
for a reader who never opens the source code.

Never commit TED-LIUM, MuST-C, IWSLT, SponSpeech, Switchboard, or Fisher
material -- all are CC BY-NC / CC BY-NC-ND or LDC-paid. Never commit
Svarah, IndicVoices, IndicVoices-R, Kathbath, Shrutilipi, or AI4Bharat's
NPTEL2020 either -- empirically punctuation-stripped (Svarah also has no
stated license anywhere), so even leaving licensing aside they cannot
measure what a formatting-restoration fixture claims to measure. See
`BLOCKED_SOURCES`.

------------------------------------------------------------------------
UPSTREAM REVISIONS ARE PINNED
------------------------------------------------------------------------
Each source records the exact upstream revision its fixture was built
from (`revision` in `SOURCES`): a git commit SHA for the GitHub sources, a
repo SHA for the Hugging Face one, a SHA-256 of the archive for
LibriSpeech-PC, which is served from a plain mirror with no revisions at
all. Every fetch either requests that exact revision or verifies it after
the fact and raises. Re-running therefore reproduces byte-identical
fixtures, or fails loudly -- it cannot silently produce different data
because upstream moved.
"""

import difflib
import hashlib
import io
import json
import random
import re
import sys
import tarfile
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

USER_AGENT = "butterfly-speak-fetch-corpora/1 (+https://github.com/)"
TIMEOUT = 60

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures"
CACHE_DIR = Path(__file__).resolve().parent / ".cache"

# Fixed seed: re-running this script reproduces byte-identical fixture
# files (given unchanged upstream data), so a diff after a re-run means the
# upstream source actually changed, not that our sampling did.
SAMPLE_SEED = 20260818

TARGET_SAMPLE_SIZE = 200


# ---------------------------------------------------------------------------
# The allow-list.
# ---------------------------------------------------------------------------

# The gate. A fixture may be written only if the license recorded for its
# source is one of these EXACT strings -- the two Creative Commons licenses
# that permit commercial use and redistribution of derivatives, which is
# what shipping a sampled fixture inside this repo is.
#
# Gating the license value rather than the source key is the whole point:
# a key can be added to `SOURCES` in a one-line diff, but a non-commercial
# or unlicensed source cannot pass this set no matter what it is called.
# Anything not listed here -- CC BY-NC*, CC BY-ND*, CC0 (fine in substance
# but never yet verified for a source here, so it must be reviewed before
# being added), an LDC agreement, or no license at all -- is refused.
ALLOWED_LICENSES = frozenset(
    {
        "CC BY 4.0",
        "CC BY-SA 4.0",
    }
)

# ---------------------------------------------------------------------------
# Pinned upstream revisions.
#
# Without these the fixtures are reproducible only until upstream moves --
# a re-run would silently produce different cases and the diff would look
# like this script changed. Each constant is the revision the committed
# fixtures were actually built from, and each fetcher either requests that
# exact revision (GitHub raw serves any commit-ish in the path) or checks
# it after downloading and raises on mismatch.
#
# To move a pin: bump it here, re-run, and review the fixture diff. Never
# bump one to make a failing check pass without looking at that diff.
# ---------------------------------------------------------------------------

# revdotcom/speech-datasets @ main, HEAD at fetch time. Supplies both
# Earnings-22 fixtures.
_REVDOTCOM_COMMIT = "c05ab6fd8b4b627d123c922a22a39e993dd37635"
# google-research-datasets/Disfl-QA @ main, HEAD at fetch time (the repo
# has not changed since 2021).
_DISFLQA_COMMIT = "1f0c16171c77b3d3408be92c485f11b8998a9189"
# sarvamai/indic-diarbench: the Hugging Face repo SHA. The datasets-server
# /rows endpoint has no revision parameter, so `fetch_indic_diarbench`
# verifies this against the repo API instead of pinning the request.
_DIARBENCH_REVISION = "92877bad8aab6e598167d91c6ee02aa8ca6ede09"
# openslr.org/145 manifests.tar.gz: no revisions exist, so the pin is the
# content hash of the archive itself.
_LSPC_SHA256 = "96d4eae2222b29b66437a21959252419bcd4762e5042e71e023790171054d1c0"

SOURCES = {
    "librispeech-pc": {
        "name": "LibriSpeech-PC",
        "url": "https://www.openslr.org/145/",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "license_evidence": (
            "LICENSE.txt inside manifests.tar.gz itself: 'The LibriSpeech-PC "
            "Dataset is made available by NVIDIA CORPORATION under a "
            "Creative Commons Attribution 4.0 International License.'"
        ),
        "citation": (
            "A. Meister, M. Novikov, N. Karpov, E. Bakhturina, V. Lavrukhin, "
            "B. Ginsburg, \"LibriSpeech-PC: Benchmark for Evaluation of "
            "Punctuation and Capitalization Capabilities of end-to-end ASR "
            "Models,\" arXiv:2310.02943, 2023."
        ),
        "caveat": (
            "READ speech: LibriVox volunteers reading pre-1928 Gutenberg "
            "prose, via the original LibriSpeech corpus. Zero fillers, and "
            "a comma distribution drawn from long literary sentences. It "
            "measures punctuation/casing restoration and NOTHING about "
            "disfluency -- optimizing the formatter against this corpus "
            "alone could actively harm real dictation output. Treat it as "
            "a regression guard, not a target."
        ),
        # openslr.org serves a static archive with no revisions of any
        # kind, so the only thing that can be pinned is the bytes.
        # `fetch_librispeech_pc` hashes the download and raises on
        # mismatch.
        "revision": f"sha256:{_LSPC_SHA256}",
        "revision_kind": "sha256 of manifests.tar.gz",
    },
    "earnings22": {
        "name": "Earnings-22",
        "url": "https://github.com/revdotcom/speech-datasets/tree/main/earnings22",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "license_evidence": (
            "earnings22/LICENSE.md in the repo: 'The transcripts and "
            "associated text files that are used for alignment in this "
            "directory are licensed under a Creative Commons "
            "Attribution-ShareAlike 4.0 International license.'"
        ),
        "citation": (
            "M. Del Rio et al., \"Earnings-22: A Practical Benchmark for "
            "Accents in Speech Recognition,\" Research in Language 21(3), "
            "2023 (arXiv:2203.15591)."
        ),
        "caveat": (
            "Spontaneous speech (earnings calls), real fillers ('um'/'uh' "
            "appear as ordinary tokens on BOTH sides here). This entry "
            "covers the full 125-call corpus, whose "
            "transcripts/nlp_references/*.nlp are verbatim, token-level, "
            "punctuation+case-tagged references -- one transcript per "
            "call, so on its own it supports kind=punctuation only. The "
            "verbatim/non-verbatim PAIR a disfluency fixture needs "
            "does exist, for ten of these calls, under "
            "earnings22/subset10/ -- see the separate "
            "`earnings22-subset10` source, which is where every "
            "kind=disfluency case from Earnings-22 comes from. None of the "
            "ten subset10 calls appears in the sample here -- asserted in "
            "the fetch script -- so the punctuation and disfluency "
            "fixtures share no audio and no transcript text."
        ),
        "revision": _REVDOTCOM_COMMIT,
        "revision_kind": "git commit (github.com/revdotcom/speech-datasets)",
    },
    "earnings22-subset10": {
        "name": "Earnings-22 Subset 10",
        "url": (
            "https://github.com/revdotcom/speech-datasets/tree/main/"
            "earnings22/subset10"
        ),
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "license_evidence": (
            "earnings22/subset10/LICENSE.md, the subset's OWN license file "
            "(not inherited from the parent directory): 'The transcripts "
            "and associated text files that are used for alignment in this "
            "directory are licensed under a Creative Commons "
            "Attribution-ShareAlike 4.0 International license.'"
        ),
        "citation": (
            "Q. McNamara, M. A. del Rio Fernandez, N. Bhandari, M. "
            "Ratajczak, D. Chen, C. Miller, M. Jette, \"Style-agnostic "
            "evaluation of ASR using multiple reference transcripts,\" "
            "arXiv:2412.07937, 2024 -- the paper describing this subset's "
            "creation; the underlying calls are Earnings-22 (Del Rio et "
            "al., Research in Language 21(3), 2023)."
        ),
        "caveat": (
            "THE VERBATIM/NON-VERBATIM PAIR. Ten Earnings-22 calls "
            "were re-transcribed in a second style and shipped under "
            "earnings22/subset10/. Its README states the difference "
            "first-hand: 'The verbatim transcripts are created by the "
            "transcriptionists writing exactly what they hear, including "
            "filler words, stutters, interjections (active listening) and "
            "repetitions. The nonverbatim transcripts are created by "
            "lightly editing for readability without changing the "
            "structure or meaning of the speech.' Why it is easy to miss: "
            "subset10/verbatim_transcripts/nlp_references/*.nlp are git "
            "SYMLINKS (mode 120000) back to "
            "../../../transcripts/nlp_references/*.nlp, so the verbatim "
            "half looks identical to the full corpus and only "
            "subset10/nonverbatim_transcripts/ is new. Looking only at "
            "earnings22/transcripts/ therefore shows one transcript per "
            "call and nothing else, which is the wrong conclusion. "
            "HOW THE CASES ARE DERIVED, since upstream ships no "
            "sentence-level alignment: the two token streams are aligned "
            "with difflib, cut into units only where BOTH sides end a "
            "sentence at the same aligned token, and a unit is kept only "
            "if it is DELETION-ONLY -- the non-verbatim side is the "
            "verbatim side with whole tokens deleted and, on each token "
            "that survives, punctuation characters deleted; nothing "
            "inserted, nothing substituted, nothing re-cased, punctuation "
            "included -- AND every deleted run is a recognisable "
            "disfluency: a filler ('uh', 'um', ...), an immediate "
            "repetition of a word that SURVIVES next to it, or a false "
            "start (Rev marks these with a trailing hyphen, e.g. "
            "'curren-'). Punctuation may vanish because that is a "
            "mechanical consequence of the deletion -- the commas in "
            "'So, obviously higher margins, uh, excluding those sales.' "
            "exist only to set off the filler -- but punctuation that is "
            "ADDED ('So' -> 'So,'), SWAPPED ('detail.' -> 'detail?') or "
            "used to merge two sentences into one ('CapEx. Um, our "
            "guidance' -> 'CapEx, our guidance') is a rewrite and the "
            "unit is discarded, as it is where the transcriptionist also "
            "reworded ('gonna' -> 'going to'), corrected a mishearing, "
            "dropped an ordinary word, or restyled capitalisation. Those "
            "are editorial choices a formatter cannot be expected to "
            "reproduce, and scoring them would put an unreachable ceiling "
            "on the metric. 260 of 4566 candidate units survive (5.7%); "
            "the script prints this on every run. "
            "WHAT THIS FIXTURE THEREFORE DOES NOT MEASURE, which is a "
            "consequence of the filter's construction and not a sampling "
            "accident: SELF-CORRECTIONS ('we grew three, sorry, four "
            "percent') and RESTARTS that are not hyphen-marked are absent "
            "by design. A correction replaces one word with a different "
            "one, so the aligner sees a `replace` and the unit is "
            "discarded; an abandoned phrase that Rev did not mark with a "
            "trailing hyphen is an unexplained deletion and is discarded "
            "too. The tag counts on the committed sample show the shape "
            "of what is left: filler 152, repetition 79, false-start 13 "
            "out of 200 cases. So this fixture measures REMOVAL OF "
            "FILLERS AND REPETITIONS well, false starts thinly, and "
            "self-corrections not at all -- and it does not measure the "
            "full verbatim-to-readable rewrite Rev's transcriptionists "
            "actually performed. Disfl-QA is the complement here: over "
            "90% of ITS disfluencies are corrections and restarts, but it "
            "is written text rather than speech."
        ),
        "revision": _REVDOTCOM_COMMIT,
        "revision_kind": "git commit (github.com/revdotcom/speech-datasets)",
    },
    "disflqa": {
        "name": "Disfl-QA",
        "url": "https://github.com/google-research-datasets/Disfl-QA",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "license_evidence": (
            "README.md, '## License' section: 'Disfl-QA dataset is "
            "licensed under CC BY 4.0.'"
        ),
        "citation": (
            "A. Gupta, J. Xu, S. Upadhyay, D. Yang, M. Faruqui, \"Disfl-QA: "
            "A Benchmark Dataset for Understanding Disfluencies in Question "
            "Answering,\" Findings of ACL, 2021."
        ),
        "caveat": (
            "~12k (disfluent, original) question pairs built on SQuAD-v2; "
            "over 90% of disfluencies are corrections or restarts. Written "
            "text, not ASR transcripts -- both sides start already cased "
            "and punctuated, so `verbatim` here carries the disfluent "
            "question in its original casing/punctuation and `input` is "
            "`tools/fetch_corpora.py`'s lowercase/unpunctuated simulation "
            "of it."
        ),
        "revision": _DISFLQA_COMMIT,
        "revision_kind": "git commit (github.com/google-research-datasets/Disfl-QA)",
    },
    "indic-diarbench": {
        "name": "Indic DiarBench (sarvamai/indic-diarbench)",
        "url": "https://huggingface.co/datasets/sarvamai/indic-diarbench",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "license_evidence": (
            "Hugging Face dataset card metadata, machine-readable: "
            "cardData.license == \"cc-by-4.0\" (confirmed via "
            "https://huggingface.co/api/datasets/sarvamai/indic-diarbench)."
        ),
        "citation": (
            "Sarvam AI, \"Indic DiarBench: A Multilingual Joint "
            "Diarization and ASR Benchmark for Indian Languages,\" "
            "Interspeech 2026 (arXiv:2607.23808)."
        ),
        "caveat": (
            "REGIONAL-LANGUAGE REGRESSION GUARD, NOT A QUALITY TARGET -- "
            "this project's stated priority is English formatting first. "
            "Natural multi-speaker conversational Hindi with real "
            "Devanagari danda punctuation, published by this app's own "
            "ASR vendor. Scoped to the Hindi config only, out of the 22 "
            "languages the full benchmark covers, and audio is never "
            "downloaded, only the `annotated_transcript` text. Segments "
            "that are pure non-speech tags (<noise>, <unintelligible>, "
            "<background_speech>) are dropped rather than treated as "
            "text. "
            "MEASURED ANNOTATION ARTIFACT, do not read a score here "
            "without it: this benchmark glosses code-mixed and "
            "spelled-out words by appending the Latin-script or numeric "
            "form in parentheses -- 'एग्जेग्टली(exactly)', 'तीस(30)'. "
            "Counted over the committed sample, 69.5% of cases contain at "
            "least one such gloss and parentheses are 956 of the 1432 "
            "restorable punctuation marks (67%) -- so a majority of the "
            "punctuation 'restoration' being scored is really reinstating "
            "a transcription convention, not a formatting behaviour any "
            "dictation user wants (no formatter can derive '(30)' from "
            "the spelled-out word). Those cases are TAGGED rather than "
            "dropped, because dropping them would shrink an intentional "
            "regression guard: `english-gloss` marks a case containing "
            "any such gloss, and `gloss-dominated` marks the subset where "
            "parentheses are at least half that case's punctuation. A "
            "report should separate them, and should not present the "
            "gloss-dominated subset as a formatting-quality number."
        ),
        "revision": _DIARBENCH_REVISION,
        "revision_kind": "Hugging Face repo SHA (huggingface.co/datasets/sarvamai/indic-diarbench)",
    },
}

ALLOWED_SOURCES = frozenset(SOURCES.keys())

# Investigated for this project and INTENTIONALLY left out of `SOURCES`.
# Keeping them here means the next person who wonders "why isn't DISCO in
# here, it says CC BY 4.0" finds the answer next to the code, not by
# re-deriving it.
PENDING_SOURCES = {
    "disco": {
        "name": "DISCO (vineet2104/DISCO)",
        "url": "https://github.com/vineet2104/DISCO",
        "claimed_license": "CC BY 4.0 (as declared on the paper, arXiv:2310.16749)",
        "why_excluded": (
            "No first-party license grant could be found for the DATA. "
            "Re-verified against the repository's full recursive git tree "
            "at commit b91a9e8d43cbfbefb9d7b0ff836c18d9a676943d (17 "
            "entries, untruncated): no LICENSE/COPYING file anywhere, and "
            "no license section in README.md. "
            "WHAT THE CC BY 4.0 ON THE PAPER ACTUALLY IS: arXiv:2310.16749 "
            "really does declare CC BY 4.0 on its abs page, and that is "
            "an author-selected license, not a default -- arXiv states "
            "that permission 'is granted through a license, chosen by the "
            "submitter', from CC BY 4.0 / CC BY-SA 4.0 / CC BY-NC-SA 4.0 "
            "/ CC BY-NC-ND 4.0 / arXiv's own perpetual non-exclusive "
            "license 1.0 / CC Zero, per version (verified against "
            "https://arxiv.org/help/license). It is a deliberate grant "
            "and it covers THE ARTICLE. It says nothing about a dataset "
            "distributed from a separate GitHub repository, which is what "
            "would actually be redistributed here, and that repository "
            "carries no grant at all. Reading a license on the paper as a "
            "license on the data is exactly the mistake this allow-list "
            "exists to prevent. "
            "Do not move this into SOURCES without an explicit, "
            "first-party license statement covering the data -- e.g. the "
            "authors adding a LICENSE file, or a written grant. If that "
            "ever happens: the data is "
            "data/labeled-data/{English,Hindi}.xlsx, sheet "
            "'{en,hi}-disfluent-sentences-labelled', columns 'Disfluent "
            "Sentence' -> input source and 'Fluent Sentence' / 'Hindi "
            "Fluent Sentence' -> target (needs openpyxl to read; verified "
            "present but not vendored here since this path is unused)."
        ),
    },
}

# Sources that were researched and are actively unsafe to add -- never
# route these through write_fixture(), and never add them to SOURCES.
BLOCKED_SOURCES = {
    "ted-lium": "CC BY-NC-ND 3.0 -- non-commercial, no derivatives.",
    "must-c": "CC BY-NC-ND 4.0 -- non-commercial, no derivatives.",
    "iwslt": "Constituent sets are CC BY-NC-ND -- non-commercial.",
    "sponspeech": "CC BY-NC 4.0 -- non-commercial.",
    "switchboard": "LDC paid license, not redistributable.",
    "fisher": "LDC paid license, not redistributable.",
    "svarah": (
        "No stated license anywhere, AND empirically punctuation-stripped "
        "-- would not measure formatting restoration even if licensing "
        "were resolved."
    ),
    "indicvoices": "Empirically punctuation-stripped.",
    "indicvoices-r": "Empirically punctuation-stripped.",
    "kathbath": "Empirically punctuation-stripped.",
    "shrutilipi": "Empirically punctuation-stripped.",
    "nptel2020": (
        "AI4Bharat's NPTEL2020: empirically punctuation-stripped AND "
        "all-caps."
    ),
}

assert ALLOWED_SOURCES.isdisjoint(PENDING_SOURCES), (
    "a source cannot be simultaneously approved and pending review"
)
assert ALLOWED_SOURCES.isdisjoint(BLOCKED_SOURCES), (
    "a source cannot be simultaneously approved and blocked"
)

# Required metadata. A source missing any of these would silently produce a
# LICENSE.md/sources.json entry with a hole in it, which is how an
# unattributed or uncaveated corpus gets shipped.
_REQUIRED_SOURCE_FIELDS = (
    "name",
    "url",
    "license",
    "license_url",
    "license_evidence",
    "citation",
    "caveat",
    "revision",
    "revision_kind",
)


def check_license(source_key, license_name):
    """Raises unless `license_name` is one this repo may actually ship.

    THE GATE (see the module docstring). Deliberately takes the license
    VALUE, not the source key: gating on the key would let a contributor
    add a CC BY-NC row to `SOURCES` and have it written out, with its
    non-commercial license faithfully recorded in LICENSE.md, and nothing
    anywhere refusing.
    """
    if license_name not in ALLOWED_LICENSES:
        raise ValueError(
            f"refusing to write fixtures for {source_key!r}: its recorded "
            f"license {license_name!r} is not one this repo may "
            f"redistribute. Allowed: {sorted(ALLOWED_LICENSES)}. Being "
            f"listed in SOURCES is not sufficient -- the license itself is "
            f"the gate."
        )


def _validate_sources():
    """Import-time check, so a bad `SOURCES` row fails before any network
    call rather than after a fixture has already been written."""
    for key, meta in SOURCES.items():
        missing = [f for f in _REQUIRED_SOURCE_FIELDS if not meta.get(f)]
        if missing:
            raise ValueError(f"SOURCES[{key!r}] is missing required fields: {missing}")
        check_license(key, meta["license"])


_validate_sources()


def write_fixture(source_key, cases):
    """The one function allowed to write case data under tests/fixtures/.

    Refuses -- raises, writes nothing -- unless `source_key` is a key of
    `SOURCES` AND the license recorded there is in `ALLOWED_LICENSES`.
    This is the actual enforcement, not just a comment: every fetch_*
    function below funnels through this.
    """
    if source_key in BLOCKED_SOURCES:
        raise ValueError(
            f"refusing to write fixtures for {source_key!r}: this source is "
            f"on the explicit block-list. Reason: {BLOCKED_SOURCES[source_key]}"
        )
    if source_key in PENDING_SOURCES:
        raise ValueError(
            f"refusing to write fixtures for {source_key!r}: license not "
            f"yet verified. {PENDING_SOURCES[source_key]['why_excluded']}"
        )
    # Checked against the live `SOURCES` table, not the `ALLOWED_SOURCES`
    # snapshot: the snapshot is for the import-time consistency asserts,
    # and a check that read it could disagree with the table the license
    # is then read from.
    if source_key not in SOURCES:
        raise ValueError(
            f"refusing to write fixtures for {source_key!r}: not on the "
            f"license-verified allow-list {sorted(SOURCES)}. Add it to "
            f"SOURCES in this file first, with a first-party license "
            f"citation, before writing any fixture for it."
        )
    # The real gate: what the license SAYS, not what the key is called.
    check_license(source_key, SOURCES[source_key]["license"])
    if not cases:
        raise ValueError(f"{source_key}: refusing to write an empty fixture file")

    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = FIXTURES_DIR / f"{source_key}.jsonl"
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        for case in cases:
            # Insertion order, not sort_keys: matches the field order of
            # the fixture format in the module doc (id, source, kind, lang,
            # input, target[, verbatim][, tags]). JSON object key order carries no
            # semantic meaning, so this is purely for human diffing.
            f.write(json.dumps(case, ensure_ascii=False))
            f.write("\n")
    print(f"wrote {len(cases)} cases -> {out_path.relative_to(REPO_ROOT)}")
    return out_path


# ---------------------------------------------------------------------------
# Shared conversion helpers.
# ---------------------------------------------------------------------------

# Word-internal characters that stay glued to their word instead of being
# treated as restorable punctuation -- the same choice eval::per's own
# tokenizer makes for hyphens and quotes (see its module doc: "Every other
# character -- hyphen, quote, dash, combining mark -- is glued into the
# current word rather than dropped").
_KEEP_PUNCT = {"'", "-"}


def strip_to_raw(text):
    """Simulates raw, lowercase, unpunctuated ASR output from text that is
    already correctly cased and punctuated -- the strip-and-restore half of
    the AssemblyAI Universal-2-TF methodology this whole corpus is built on.

    Removes every character in Unicode general category P* (periods,
    commas, question/exclamation marks, quotes, brackets, em/en dashes,
    ellipses, and the Devanagari danda/double danda ।॥ alike), except
    the ASCII apostrophe and hyphen-minus, which are left glued to their
    word (see `_KEEP_PUNCT`). A removed character becomes a space, not
    nothing, so words never fuse across it: "well-known," -> "well-known"
    keeps the hyphen, drops the comma, and still has a word boundary where
    the comma was.

    Uses `unicodedata.category()`, not a `\\w`-based regex, on purpose:
    Python's `\\w` excludes the Unicode combining-mark categories Mn/Mc that
    Devanagari vowel signs and the virama are made of, so an allow-list
    regex shatters matra-bearing words -- see per_oracle.py's docstring and
    eval/per.rs's module doc for the identical trap in this repo's other
    Python/Rust pair. A punctuation-category DENYLIST never touches a
    combining mark, so it cannot make that mistake, and it is exactly the
    boundary this corpus needs: strip marks, keep every letter whole.
    """
    out = []
    for ch in text:
        if ch in _KEEP_PUNCT:
            out.append(ch)
        elif unicodedata.category(ch).startswith("P"):
            out.append(" ")
        else:
            out.append(ch)
    return re.sub(r"\s+", " ", "".join(out), flags=re.UNICODE).strip().lower()


def sample_cases(cases, n=TARGET_SAMPLE_SIZE, seed=SAMPLE_SEED):
    """Deterministic sample of up to `n` cases, order-independent of the
    input list's order (sorted by id first) so re-runs are reproducible
    even if an upstream source reorders rows between fetches."""
    ordered = sorted(cases, key=lambda c: c["id"])
    if len(ordered) <= n:
        return ordered
    rng = random.Random(seed)
    return sorted(rng.sample(ordered, n), key=lambda c: c["id"])


def http_get(url, cache_name=None):
    """GET `url`, using tools/.cache/<cache_name> as a read-through cache
    when given. Raises with the URL in the message on any failure -- a
    fixture silently built from a truncated/failed download is worse than
    this script refusing to run."""
    if cache_name:
        cache_path = CACHE_DIR / cache_name
        if cache_path.exists():
            return cache_path.read_bytes()
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            data = resp.read()
    except (urllib.error.URLError, TimeoutError) as e:
        raise RuntimeError(f"fetching {url}: {e}") from e
    if cache_name:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        cache_path.write_bytes(data)
    return data


def http_get_json(url, cache_name=None):
    return json.loads(http_get(url, cache_name).decode("utf-8"))


# ---------------------------------------------------------------------------
# LibriSpeech-PC
# ---------------------------------------------------------------------------

# Mirrors listed on https://www.openslr.org/145/, tried in order.
_LSPC_MIRRORS = [
    "https://openslr.trmal.net/resources/145/manifests.tar.gz",
    "https://openslr.elda.org/resources/145/manifests.tar.gz",
    "https://openslr.magicdatatech.com/resources/145/manifests.tar.gz",
]


def fetch_librispeech_pc():
    cache_path = CACHE_DIR / "librispeech-pc-manifests.tar.gz"
    if cache_path.exists():
        data = cache_path.read_bytes()
    else:
        data = None
        errors = []
        for url in _LSPC_MIRRORS:
            try:
                data = http_get(url)
                break
            except RuntimeError as e:
                errors.append(str(e))
        if data is None:
            raise RuntimeError(
                "librispeech-pc: all mirrors failed:\n" + "\n".join(errors)
            )
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        cache_path.write_bytes(data)

    # The revision pin. openslr serves a static archive with no version
    # metadata, and the three mirrors are independently operated, so the
    # only honest pin is the bytes -- this also catches a mirror serving a
    # truncated or substituted file.
    digest = hashlib.sha256(data).hexdigest()
    if digest != _LSPC_SHA256:
        raise RuntimeError(
            f"librispeech-pc: manifests.tar.gz sha256 is {digest}, expected "
            f"{_LSPC_SHA256}. Upstream changed (or a mirror served something "
            f"else). Do not bump _LSPC_SHA256 without reviewing the fixture "
            f"diff a re-run produces."
        )

    cases = []
    with tarfile.open(fileobj=io.BytesIO(data)) as tar:
        # test-clean: the split this project's fixture ids are named after
        # ("lspc-test-clean-NNNN"), and it is the LibriSpeech split most
        # readers will recognize.
        member = tar.getmember("test-clean.json")
        manifest_text = tar.extractfile(member).read().decode("utf-8")

    for i, line in enumerate(manifest_text.splitlines()):
        line = line.strip()
        if not line:
            continue
        row = json.loads(line)
        target = row["text"].strip()
        if not target:
            continue
        raw_input = strip_to_raw(target)
        if not raw_input:
            continue
        cases.append(
            {
                "id": f"lspc-test-clean-{i:04d}",
                "source": "librispeech-pc",
                "kind": "punctuation",
                "lang": "en",
                "input": raw_input,
                "target": target,
            }
        )
    return cases


# ---------------------------------------------------------------------------
# Earnings-22
# ---------------------------------------------------------------------------

# Pinned to a commit, not `main`: `main` is whatever upstream pushed last.
_REVDOTCOM_RAW = (
    f"https://raw.githubusercontent.com/revdotcom/speech-datasets/"
    f"{_REVDOTCOM_COMMIT}/"
)
_EARNINGS22_RAW = _REVDOTCOM_RAW + "earnings22/transcripts/nlp_references/"

# A fixed, spread-out subset of the 125 available calls (every 13th
# filename, alphabetically) -- enough distinct speakers/companies for a
# ~200-sentence sample without downloading all 125 files on every run.
# None of these is one of the ten subset10 calls (see
# _EARNINGS22_SUBSET10_CALLS, and the assertion below), so the
# punctuation fixture and the disfluency fixture share no audio and no
# transcript text.
_EARNINGS22_FILES = [
    "2020-03-0230487MTN-Ghana-2019-Annual-Results-Call.nlp",
    "4448760.nlp",
    "4466251.nlp",
    "4468654.nlp",
    "4469836.nlp",
    "4472895.nlp",
    "4481221.nlp",
    "4482609.nlp",
    "4483589.nlp",
    "4484563.nlp",
]

_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.?!])\s+")


def _parse_nlp_rows(nlp_text):
    """Rev's `.nlp` format: a pipe-delimited header line
    (token|speaker|ts|endTs|punctuation|prepunctuation|case|tags) then one
    row per token. Rows whose field count disagrees with the header, and
    rows with an empty token, are dropped."""
    lines = nlp_text.splitlines()
    header = lines[0].split("|")
    rows = []
    for line in lines[1:]:
        if not line:
            continue
        fields = line.split("|")
        if len(fields) != len(header):
            continue
        row = dict(zip(header, fields))
        if not row.get("token"):
            continue
        rows.append(row)
    return rows


def _render_nlp_rows(rows):
    return " ".join(
        (r.get("prepunctuation") or "") + r["token"] + (r.get("punctuation") or "")
        for r in rows
    )


def _reconstruct_earnings22_text(nlp_text):
    return _render_nlp_rows(_parse_nlp_rows(nlp_text))


def fetch_earnings22():
    cases = []
    counter = 0
    for filename in _EARNINGS22_FILES:
        cache_name = f"earnings22-{filename}"
        data = http_get(_EARNINGS22_RAW + urllib.parse.quote(filename), cache_name)
        text = data.decode("utf-8")
        full_text = _reconstruct_earnings22_text(text)
        for sentence in _SENTENCE_SPLIT_RE.split(full_text):
            sentence = sentence.strip()
            words = sentence.split()
            if not (4 <= len(words) <= 40):
                continue
            raw_input = strip_to_raw(sentence)
            if not raw_input:
                continue
            counter += 1
            cases.append(
                {
                    "id": f"earnings22-{counter:04d}",
                    "source": "earnings22",
                    "kind": "punctuation",
                    "lang": "en",
                    "input": raw_input,
                    "target": sentence,
                }
            )
    return cases


# ---------------------------------------------------------------------------
# Earnings-22 Subset 10 -- the verbatim/non-verbatim pair.
#
# The ten calls Rev re-transcribed in a second, lightly-edited style. Both
# styles are shipped, which is what makes kind=disfluency possible from
# real spontaneous speech rather than from written text.
#
# The layout trap: subset10/verbatim_transcripts/nlp_references/*.nlp are git
# SYMLINKS (mode 120000) whose blob content is the literal string
# "../../../transcripts/nlp_references/<call>.nlp". Fetching that path from
# raw.githubusercontent.com returns the LINK TEXT, not a transcript, so the
# link is resolved here explicitly. The verbatim side is therefore
# byte-identical to the full corpus's transcript -- which is exactly why
# looking only at earnings22/transcripts/ makes it appear that no second
# style exists.
# ---------------------------------------------------------------------------

_EARNINGS22_SUBSET10_CALLS = [
    "4453225",
    "4469088",
    "4470684",
    "4474506",
    "4479944",
    "4481952",
    "4482383",
    "4482613",
    "4483937",
    "4485192",
]

assert not (
    {f"{c}.nlp" for c in _EARNINGS22_SUBSET10_CALLS} & set(_EARNINGS22_FILES)
), "the punctuation sample must not reuse a call the disfluency sample uses"

_SUBSET10_NONVERBATIM = (
    _REVDOTCOM_RAW + "earnings22/subset10/nonverbatim_transcripts/nlp_references/"
)

# Filler words as Rev's transcriptionists write them. Deliberately short
# and literal: this list decides what counts as a disfluency, so anything
# that is merely a *discourse marker* ("so", "well", "you know", "I mean")
# is NOT here. Removing those changes meaning and register, and a formatter
# that did it would be wrong.
_FILLER_TOKENS = frozenset(
    {
        "uh",
        "um",
        "umm",
        "uhm",
        "erm",
        "er",
        "ah",
        "eh",
        "mm",
        "hm",
        "hmm",
        "mhm",
        "uhhuh",
        "mmhmm",
    }
)

# Rev marks a false start / cut-off word with a trailing hyphen: "curren-",
# "re-", "aco-". Verified against the shipped transcripts.
_FALSE_START_RE = re.compile(r"[-–—]$")

# A token carrying an annotation rather than speech.
_NLP_ANNOTATION_RE = re.compile(r"[<>\[\]]")

# Sentence-final punctuation after these is an abbreviation's period, not a
# sentence boundary, so it must not become a cut point ("...introduce you to
# Mr. Sean" would otherwise be cut after "Mr."). Only tokens that are
# essentially always abbreviations: "No." is deliberately absent, because in
# this corpus "no." far more often ends a sentence than numbers one.
_ABBREVIATIONS = frozenset(
    {
        "mr",
        "mrs",
        "ms",
        "dr",
        "prof",
        "sr",
        "jr",
        "st",
        "inc",
        "ltd",
        "co",
        "corp",
        "vs",
        "etc",
        "approx",
    }
)


def _nlp_word(token):
    """Comparison key for aligning the two transcript styles: case- and
    punctuation-insensitive, so the alignment sees word identity only and
    a restyled capital or a moved comma is not mistaken for a word change.
    Surface differences are checked separately, and rejected."""
    return re.sub(r"[^\w']", "", token.lower(), flags=re.UNICODE)


def _render_row(row):
    """One `.nlp` row as it appears in the rendered text -- the same
    concatenation `_render_nlp_rows` performs, for a single row."""
    return (row.get("prepunctuation") or "") + row["token"] + (row.get("punctuation") or "")


def _is_subsequence(needle, haystack):
    """True iff `needle` can be obtained from `haystack` by deleting
    characters and nothing else. Greedy left-to-right matching, which is
    exact for subsequence testing (the earliest match always leaves the
    longest remaining haystack)."""
    it = iter(haystack)
    return all(ch in it for ch in needle)


def _ends_sentence(row):
    token = _nlp_word(row["token"])
    if token in _ABBREVIATIONS:
        return False
    return bool(re.search(r"[.?!]", row.get("punctuation") or ""))


def _classify_removal(verbatim_rows, i1, i2):
    """Why were `verbatim_rows[i1:i2]` dropped from the non-verbatim style?

    Returns a sorted list of reasons -- some subset of {"filler",
    "repetition", "false-start"} -- or None if any removed token cannot be
    explained by one of them.

    None is the important case. Rev's transcriptionists also reworded for
    readability ("gonna" -> "going to"), dropped ordinary articles, and
    fixed mishearings. Those are editorial judgements about someone else's
    speech; a dictation formatter neither can nor should reproduce them,
    and a fixture that demanded it would cap the achievable score at
    something meaningless. Anything unexplained here means the whole unit
    is discarded.
    """
    removed = [_nlp_word(r["token"]) for r in verbatim_rows[i1:i2]]
    span = i2 - i1
    if not removed:
        return None

    # Whole-span immediate repetition: "on the, on the chart" (the span
    # repeats what directly follows) or "are, are, are looking" (it repeats
    # what directly precedes).
    following = [_nlp_word(r["token"]) for r in verbatim_rows[i2 : i2 + span]]
    preceding = [_nlp_word(r["token"]) for r in verbatim_rows[max(0, i1 - span) : i1]]
    if removed in (following, preceding):
        return ["repetition"]

    # Per-token fallback. A removed word counts as a repetition only when
    # the copy it duplicates SURVIVES -- these two are the surviving
    # neighbours of the whole removed run (difflib emits maximal runs, so
    # the rows either side of a `delete` are not themselves deleted).
    #
    # Comparing a removed token against its removed NEIGHBOURS would call
    # an outright word deletion a repetition: "in the the chart" -> "in
    # chart" removes BOTH copies of "the", and each copy would then "match"
    # the other. Nothing is de-duplicated there; the transcriptionist
    # dropped the word, which is an editorial edit and belongs in the
    # discard pile with the rest. The surviving-copy rule also stops
    # under-counting in the other direction: in "the, uh, the chart" ->
    # "the chart" the removed "the" duplicates the surviving "the" across
    # the intervening filler, which a neighbour-of-a-neighbour walk cannot
    # see.
    before = _nlp_word(verbatim_rows[i1 - 1]["token"]) if i1 else None
    after = _nlp_word(verbatim_rows[i2]["token"]) if i2 < len(verbatim_rows) else None

    reasons = set()
    for row in verbatim_rows[i1:i2]:
        word = _nlp_word(row["token"])
        if word in _FILLER_TOKENS:
            reasons.add("filler")
            continue
        if _FALSE_START_RE.search(row["token"]):
            reasons.add("false-start")
            continue
        if word and word in (before, after):
            reasons.add("repetition")
            continue
        return None
    return sorted(reasons) if reasons else None


def _subset10_units(verbatim_rows, nonverbatim_rows, stats=None):
    """Yields (verbatim_slice, nonverbatim_slice, reasons) for every
    sentence-level unit where the non-verbatim style is the verbatim style
    with disfluencies deleted and nothing else changed.

    Upstream ships no alignment between the two styles -- just two token
    streams for the same audio -- so one is derived here: align on word
    identity, cut only where BOTH sides end a sentence at the same aligned
    token (an unambiguous shared boundary), then keep a unit only if every
    edit inside it is an explained deletion.

    THE INVARIANT, STATED EXACTLY, because everything downstream leans on
    it: the non-verbatim unit is the verbatim unit with WHOLE TOKENS
    deleted and, on each token that survives, PUNCTUATION CHARACTERS
    deleted -- nothing inserted, nothing substituted, nothing re-cased,
    anywhere, punctuation included. Punctuation deletion has to be allowed
    because it is a mechanical consequence of the token deletion: the
    commas in "So, obviously higher margins, uh, excluding those sales."
    exist only to set off the filler, and requiring the clean side to keep
    them would make the TARGETS worse ("...margins, excluding..."), not the
    filter stricter. Punctuation ADDITION and SUBSTITUTION are a different
    thing entirely and are rejected: "So" -> "So," inserts a judgement the
    verbatim never made, "detail." -> "detail?" reinterprets the sentence,
    and "CapEx. Um, our guidance" -> "CapEx, our guidance" merges two
    sentences into one. Those are editorial rewrites, and they are what
    this filter exists to keep out. Without the punctuation half of the
    check they go straight through: measured on a sample built without it,
    43 of 200 cases add or swap punctuation on a surviving token, and none
    of those 43 fails the casing half -- so punctuation is the entire gap,
    not part of it.
    """
    a = [_nlp_word(r["token"]) for r in verbatim_rows]
    b = [_nlp_word(r["token"]) for r in nonverbatim_rows]
    opcodes = difflib.SequenceMatcher(a=a, b=b, autojunk=False).get_opcodes()

    cuts = [(0, 0)]
    for tag, i1, _i2, j1, j2 in opcodes:
        if tag != "equal":
            continue
        for offset in range(j2 - j1):
            if _ends_sentence(verbatim_rows[i1 + offset]) and _ends_sentence(
                nonverbatim_rows[j1 + offset]
            ):
                cuts.append((i1 + offset + 1, j1 + offset + 1))
    cuts.append((len(verbatim_rows), len(nonverbatim_rows)))

    for (i_start, j_start), (i_end, j_end) in zip(cuts, cuts[1:]):
        v_slice = verbatim_rows[i_start:i_end]
        n_slice = nonverbatim_rows[j_start:j_end]
        # Counted before every filter, length gate included, so the survival
        # rate this script prints (and the caveat quotes) has one obvious
        # denominator -- every sentence-level unit the shared-boundary cut
        # produced -- and is measured on each run rather than copied
        # forward from an older one.
        if stats is not None:
            stats["candidates"] = stats.get("candidates", 0) + 1
        if not (4 <= len(v_slice) <= 40) or len(n_slice) < 3:
            continue

        reasons = set()
        removed_tokens = 0
        ok = True
        for tag, i1, i2, j1, j2 in opcodes:
            if tag == "insert":
                # An `insert` consumes nothing on the verbatim side
                # (i1 == i2), so its verbatim index says only WHERE it sits,
                # never whether its tokens land in this unit. The question
                # that matters is on the non-verbatim side: do any of the
                # inserted rows fall inside nonverbatim_rows[j_start:j_end],
                # i.e. inside the text that becomes this unit's `target`? If
                # so the target contains a word the verbatim never had, and
                # the unit is out.
                #
                # A strict `i_start < i1 < i_end` test would miss an
                # insertion anchored exactly at the unit's LEADING boundary
                # (i1 == i_start), though its tokens sit at the front of
                # this unit's target.
                if j1 < j_end and j2 > j_start:
                    ok = False
                    break
                continue
            if i2 <= i_start or i1 >= i_end:
                continue
            if tag == "replace":
                ok = False
                break
            if tag == "delete":
                why = _classify_removal(verbatim_rows, i1, i2)
                if why is None:
                    ok = False
                    break
                reasons.update(why)
                removed_tokens += i2 - i1
        if not ok or removed_tokens == 0:
            continue

        # Every surviving token, checked on its FULL rendered surface --
        # prepunctuation + token + punctuation -- not just the word.
        #
        #   * the word itself must be byte-identical, casing included. Rev's
        #     two styles differ on things like "Regional Brands" vs
        #     "regional brands" and "Covid" vs "COVID"; that is house style,
        #     not disfluency, and scoring it here would smuggle a
        #     capitalization judgement into a disfluency metric.
        #   * the rendered surface must be a SUBSEQUENCE of the verbatim
        #     one, so punctuation may only disappear. Anything added,
        #     moved onto this token, or swapped for a different mark fails.
        #
        # The second half is needed because `punctuation` is a separate
        # `.nlp` column: a check on `row["token"]` alone would not see
        # any punctuation edit the transcriptionist made.
        #
        # Because the survivors are walked in order and inserts/replaces
        # are already rejected, this pairwise property implies the whole
        # unit's rendered text is a character-subsequence of the verbatim
        # unit's -- i.e. deletion-only holds for the unit, not just
        # token-by-token. The pairwise form is the stronger of the two and
        # is the one enforced: checking only the whole unit lets a mark
        # freed by a deletion re-appear somewhere else and still match, and
        # that is exactly how "CapEx. Um, our guidance" -> "CapEx, our
        # guidance" (a sentence merge) sneaks past.
        drift = False
        for tag, i1, i2, j1, _j2 in opcodes:
            if tag != "equal":
                continue
            for i in range(max(i1, i_start), min(i2, i_end)):
                v_row = verbatim_rows[i]
                n_row = nonverbatim_rows[j1 + (i - i1)]
                if v_row["token"] != n_row["token"] or not _is_subsequence(
                    _render_row(n_row), _render_row(v_row)
                ):
                    drift = True
                    break
            if drift:
                break
        if drift:
            continue

        yield v_slice, n_slice, sorted(reasons)


def fetch_earnings22_subset10():
    cases = []
    counter = 0
    stats = {"candidates": 0}
    for call in _EARNINGS22_SUBSET10_CALLS:
        # Resolve the symlink ourselves -- see the section comment above.
        verbatim_rows = _parse_nlp_rows(
            http_get(
                _EARNINGS22_RAW + f"{call}.nlp", f"earnings22-{call}.nlp"
            ).decode("utf-8")
        )
        nonverbatim_rows = _parse_nlp_rows(
            http_get(
                _SUBSET10_NONVERBATIM + f"{call}.nlp",
                f"earnings22-subset10-nonverbatim-{call}.nlp",
            ).decode("utf-8")
        )
        for v_slice, n_slice, reasons in _subset10_units(
            verbatim_rows, nonverbatim_rows, stats
        ):
            verbatim_text = _render_nlp_rows(v_slice)
            target_text = _render_nlp_rows(n_slice)
            if _NLP_ANNOTATION_RE.search(verbatim_text) or _NLP_ANNOTATION_RE.search(
                target_text
            ):
                continue
            raw_input = strip_to_raw(verbatim_text)
            if not raw_input:
                continue
            counter += 1
            cases.append(
                {
                    "id": f"earnings22-subset10-{counter:04d}",
                    "source": "earnings22-subset10",
                    "kind": "disfluency",
                    "lang": "en",
                    "input": raw_input,
                    "target": target_text,
                    "verbatim": verbatim_text,
                    "tags": reasons,
                }
            )
    if stats["candidates"]:
        share = 100.0 * len(cases) / stats["candidates"]
        print(
            f"earnings22-subset10: {len(cases)} of {stats['candidates']} candidate "
            f"units survive the deletion-only filter ({share:.1f}%)"
        )
    return cases


# ---------------------------------------------------------------------------
# Disfl-QA
# ---------------------------------------------------------------------------

_DISFLQA_TEST = (
    f"https://raw.githubusercontent.com/google-research-datasets/"
    f"Disfl-QA/{_DISFLQA_COMMIT}/test.json"
)

# The published test.json contains 13 pairs (out of 3643) where "disfluent"
# is literally the string "#VALUE!" -- a spreadsheet formula-error artifact
# baked into the upstream data (evidently produced through Excel/Sheets at
# some point in Disfl-QA's own pipeline), not something this script
# introduces. Confirmed by scanning the raw file directly. A handful of
# other Excel error tokens are guarded defensively even though only
# "#VALUE!" was observed, since the failure mode (a formula literal leaking
# into a text column) is generic to whatever produced this one.
_EXCEL_ERROR_RE = re.compile(r"^#(VALUE|REF|DIV/0|NAME|NULL|NUM|N/A)[!?]?$")


def fetch_disflqa():
    data = http_get_json(_DISFLQA_TEST, cache_name="disflqa-test.json")
    cases = []
    skipped_excel_errors = 0
    for i, (_qid, pair) in enumerate(sorted(data.items())):
        original = pair["original"].strip()
        disfluent = pair["disfluent"].strip()
        if not original or not disfluent:
            continue
        if _EXCEL_ERROR_RE.match(original) or _EXCEL_ERROR_RE.match(disfluent):
            skipped_excel_errors += 1
            continue
        raw_input = strip_to_raw(disfluent)
        if not raw_input:
            continue
        cases.append(
            {
                "id": f"disflqa-test-{i:04d}",
                "source": "disflqa",
                "kind": "disfluency",
                "lang": "en",
                "input": raw_input,
                "target": original,
                "verbatim": disfluent,
            }
        )
    if skipped_excel_errors:
        print(f"disflqa: skipped {skipped_excel_errors} '#VALUE!'-poisoned rows")
    return cases


# ---------------------------------------------------------------------------
# indic-diarbench (Hindi)
# ---------------------------------------------------------------------------

_DIARBENCH_ROWS_URL = (
    "https://datasets-server.huggingface.co/rows"
    "?dataset=sarvamai%2Findic-diarbench&config=Hindi&split=test"
    "&offset={offset}&length={length}"
)

_DIARBENCH_REPO_API = "https://huggingface.co/api/datasets/sarvamai/indic-diarbench"

_NONSPEECH_TAG_RE = re.compile(r"^\s*<[^<>]+>\s*$")
_PAGE_LENGTH = 20
# Enough rows to comfortably clear TARGET_SAMPLE_SIZE valid segments without
# pulling all 94 available test rows (or their audio-URL metadata) on every
# run; raise if the source's segment density ever drops.
_MAX_ROWS = 60

# This benchmark's gloss convention: a Devanagari-spelled word followed by
# its Latin-script or numeric form in parentheses --
# "इंटरव्यू(interview)", "आई-क्यू(IQ)", "सात-आठ(7-8)", "तीस(30)".
# Matches a parenthesised run that contains an ASCII letter or digit and NO
# Devanagari, so an ordinary Devanagari parenthetical aside (were one to
# appear) is not mistaken for a gloss. The digit-only form
# ("तीस(30)") is included deliberately: it is the same convention and the
# same scoring problem -- the formatter would have to invent "(30)" out of
# the spelled-out word -- and excluding it would leave a handful of cases
# carrying the artifact untagged.
_ENGLISH_GLOSS_RE = re.compile(r"\([^()ऀ-ॿ]*[A-Za-z0-9][^()ऀ-ॿ]*\)")


def _diarbench_gloss_tags(target):
    """Tags marking the parenthesised-English-gloss annotation artifact.

    `strip_to_raw` removes parentheses along with every other punctuation
    mark, so a fixture built from this source scores the formatter on
    putting them back -- i.e. on reproducing a transcription convention,
    not on any formatting behaviour a dictation user would notice. That is
    a real property of the data and it is the majority of the punctuation
    in it, so the cases carry it explicitly instead of a report having to
    rediscover it. See this source's `caveat` for the measured share.
    """
    tags = []
    if _ENGLISH_GLOSS_RE.search(target):
        tags.append("english-gloss")
        marks = [
            ch
            for ch in target
            if unicodedata.category(ch).startswith("P") and ch not in _KEEP_PUNCT
        ]
        parens = sum(1 for ch in marks if ch in "()")
        if marks and parens / len(marks) >= 0.5:
            tags.append("gloss-dominated")
    return tags


def fetch_indic_diarbench():
    # The datasets-server /rows endpoint takes no revision parameter, so
    # the pin is verified against the repo API instead: if upstream has
    # moved, this raises rather than quietly building different fixtures.
    repo = http_get_json(_DIARBENCH_REPO_API, cache_name="diarbench-repo.json")
    if repo.get("sha") != _DIARBENCH_REVISION:
        raise RuntimeError(
            f"indic-diarbench: repo is now at {repo.get('sha')!r}, fixtures "
            f"were built from {_DIARBENCH_REVISION!r}. Bump "
            f"_DIARBENCH_REVISION only after reviewing the fixture diff a "
            f"re-run produces."
        )
    # Same check for the license: the dataset card is the first-party
    # evidence, and a card can be edited.
    card_license = (repo.get("cardData") or {}).get("license")
    if card_license != "cc-by-4.0":
        raise RuntimeError(
            f"indic-diarbench: dataset card now says license={card_license!r}, "
            f"expected 'cc-by-4.0' (the first-party evidence this source is "
            f"admitted on). Refusing to build a fixture from it."
        )

    cases = []
    offset = 0
    while offset < _MAX_ROWS and len(cases) < TARGET_SAMPLE_SIZE * 3:
        url = _DIARBENCH_ROWS_URL.format(offset=offset, length=_PAGE_LENGTH)
        page = http_get_json(url, cache_name=f"diarbench-hi-{offset:03d}.json")
        rows = page.get("rows", [])
        if not rows:
            break
        for row in rows:
            for seg in row["row"]["annotated_transcript"]:
                transcript = (seg.get("transcript") or "").strip()
                if not transcript or _NONSPEECH_TAG_RE.match(transcript):
                    continue
                # Drop inline non-speech tags but keep the surrounding
                # speech ("...<noise> ..." segments do occur).
                cleaned = re.sub(r"<[^<>]+>", " ", transcript)
                cleaned = re.sub(r"\s+", " ", cleaned, flags=re.UNICODE).strip()
                if len(cleaned) < 6:
                    continue
                raw_input = strip_to_raw(cleaned)
                if not raw_input:
                    continue
                cases.append(
                    {
                        "id": f"diarbench-hi-{len(cases):04d}",
                        "source": "indic-diarbench",
                        "kind": "punctuation",
                        "lang": "hi",
                        "input": raw_input,
                        "target": cleaned,
                        "tags": _diarbench_gloss_tags(cleaned),
                    }
                )
        offset += _PAGE_LENGTH
        if not page.get("rows") or offset >= page.get("num_rows_total", offset):
            break
    return cases


# ---------------------------------------------------------------------------
# LICENSE.md generation
# ---------------------------------------------------------------------------


def write_license_md(counts=None):
    counts = counts or {}
    lines = []
    lines.append("# Fixture corpus licenses\n")
    lines.append(
        "Generated by `tools/fetch_corpora.py` -- do not hand-edit, "
        "re-run the script instead. Every file in `tests/fixtures/*.jsonl` "
        "is a ~200-case sample drawn from exactly one source below. Each "
        "license was confirmed from a first-party statement (a LICENSE "
        "file in the source's own distribution, or a license field in its "
        "own dataset card) at fetch time -- see `license_evidence` in "
        "the `SOURCES` table of `tools/fetch_corpora.py` for exactly what "
        "was checked and where.\n"
    )
    lines.append(
        "Only these licenses may be shipped from this repo: "
        + ", ".join(sorted(ALLOWED_LICENSES))
        + ". That set -- not the list of source names -- is what the fetch "
        "script actually enforces before writing a fixture.\n"
    )
    lines.append(
        "The same metadata is emitted machine-readably as "
        "`tests/fixtures/sources.json`, so a benchmark report can print "
        "each source's caveat next to its score instead of leaving it "
        "here where nobody reading a number will see it.\n"
    )
    for key, meta in SOURCES.items():
        lines.append(f"## {meta['name']} -- `{key}.jsonl`\n")
        lines.append(f"- **License:** {meta['license']} ({meta['license_url']})")
        lines.append(f"- **Evidence:** {meta['license_evidence']}")
        lines.append(f"- **Source:** {meta['url']}")
        lines.append(f"- **Revision:** {meta['revision']} ({meta['revision_kind']})")
        lines.append(f"- **Citation:** {meta['citation']}")
        lines.append(f"- **Caveat:** {meta['caveat']}")
        if key in counts:
            lines.append(f"- **Cases:** {counts[key]}")
        lines.append("")
    lines.append("## Researched but NOT included\n")
    for key, meta in PENDING_SOURCES.items():
        lines.append(f"### {meta['name']}\n")
        lines.append(f"- **Source:** {meta['url']}")
        lines.append(f"- **Claimed license:** {meta['claimed_license']}")
        lines.append(f"- **Why excluded:** {meta['why_excluded']}")
        lines.append("")
    lines.append(
        "## Never use (verified CC BY-NC / LDC-paid / punctuation-stripped "
        "-- do not add)\n"
    )
    for key, reason in sorted(BLOCKED_SOURCES.items()):
        lines.append(f"- **{key}** -- {reason}")
    lines.append("")
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = FIXTURES_DIR / "LICENSE.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# sources.json -- the same metadata, where the harness can reach it.
#
# LICENSE.md is for a human who opens tests/fixtures/. A benchmark report
# prints numbers somewhere else entirely, and a caveat that only exists in
# a Markdown file nobody has open while reading a score is not doing its
# job -- "LibriSpeech-PC is read speech, treat it as a regression guard,
# not a target" has to be printable BESIDE the LibriSpeech-PC number.
# ---------------------------------------------------------------------------


def write_sources_json(sampled_by_source):
    entries = {}
    for key, meta in SOURCES.items():
        cases = sampled_by_source.get(key)
        if cases is None:
            # A source whose fetch failed this run: its metadata still
            # belongs here, but claiming a case count would be a lie.
            counts = None
        else:
            counts = {
                "cases": len(cases),
                "kinds": sorted({c["kind"] for c in cases}),
                "langs": sorted({c["lang"] for c in cases}),
                "tags": {
                    tag: sum(1 for c in cases if tag in c.get("tags", []))
                    for tag in sorted(
                        {t for c in cases for t in c.get("tags", [])}
                    )
                },
            }
        entries[key] = {
            "name": meta["name"],
            "url": meta["url"],
            "license": meta["license"],
            "license_url": meta["license_url"],
            "license_evidence": meta["license_evidence"],
            "citation": meta["citation"],
            "caveat": meta["caveat"],
            "revision": meta["revision"],
            "revision_kind": meta["revision_kind"],
            "fixture": f"{key}.jsonl",
            **({} if counts is None else counts),
        }
    doc = {
        "generated_by": "tools/fetch_corpora.py",
        "methodology": (
            "AssemblyAI Universal-2-TF (arXiv:2501.05948): `target` is text "
            "that already has correct punctuation and casing; `input` is "
            "the same text lowercased and stripped of punctuation, "
            "simulating raw ASR output. Score = how well the formatter "
            "restores `target` from `input`."
        ),
        "allowed_licenses": sorted(ALLOWED_LICENSES),
        "sample_seed": SAMPLE_SEED,
        "target_sample_size": TARGET_SAMPLE_SIZE,
        "sources": entries,
    }
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = FIXTURES_DIR / "sources.json"
    out_path.write_text(
        json.dumps(doc, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

FETCHERS = {
    "librispeech-pc": fetch_librispeech_pc,
    "earnings22": fetch_earnings22,
    "earnings22-subset10": fetch_earnings22_subset10,
    "disflqa": fetch_disflqa,
    "indic-diarbench": fetch_indic_diarbench,
}


def _demonstrate_refusals():
    """Run the two refusals for real, BEFORE anything is fetched or written.

    Not mocked and not hypothetical: `main()` calls this first, so if either
    gate has stopped refusing, the script aborts having written nothing.
    Run at the END of `main()`, after every fixture had been written to
    disk, an "abort" would stop nothing, because the files the broken gate
    let through would already be sitting in `tests/fixtures/` for the next
    `git add`. Order is the whole mechanism here, not a detail.
    """
    # 1. A source investigated and deliberately not shipped (DISCO).
    try:
        write_fixture("disco", [{"id": "should-not-be-written"}])
    except ValueError as e:
        print(f"allow-list correctly refused 'disco': {e}")
    else:
        raise AssertionError("write_fixture('disco', ...) should have refused")

    # 2. The case that actually matters: a source WITH a SOURCES entry, a
    # plausible name, and a genuine first-party license -- that happens to
    # be non-commercial. Gating the key would let this through; gating the
    # license does not. Injected and removed here so the check runs against
    # the real write path rather than a copy of its logic.
    probe_key = "__license-gate-probe__"
    assert probe_key not in SOURCES
    SOURCES[probe_key] = {
        "name": "License gate probe",
        "url": "https://example.invalid/",
        "license": "CC BY-NC 4.0",
        "license_url": "https://creativecommons.org/licenses/by-nc/4.0/",
        "license_evidence": "n/a -- this row exists only to be refused",
        "citation": "n/a",
        "caveat": "n/a",
        "revision": "n/a",
        "revision_kind": "n/a",
    }
    try:
        write_fixture(probe_key, [{"id": "should-not-be-written"}])
    except ValueError as e:
        print(f"license gate correctly refused a CC BY-NC source: {e}")
    else:
        raise AssertionError(
            "write_fixture on a CC BY-NC source should have refused -- the "
            "gate is on the license, and it is not holding"
        )
    finally:
        del SOURCES[probe_key]
    assert not (FIXTURES_DIR / f"{probe_key}.jsonl").exists()


def main():
    assert set(FETCHERS) == ALLOWED_SOURCES, "every allowed source needs a fetcher"

    # FIRST, before a byte is fetched or written. An allow-list check that
    # runs after the fixtures are on disk cannot prevent anything; this one
    # aborts the run with nothing written.
    _demonstrate_refusals()

    failures = []
    sampled_by_source = {}
    for key, fetch in FETCHERS.items():
        print(f"--- {key} ---")
        try:
            raw_cases = fetch()
            sampled = sample_cases(raw_cases)
            print(f"{key}: {len(raw_cases)} candidates, sampling {len(sampled)}")
            write_fixture(key, sampled)
            sampled_by_source[key] = sampled
        except Exception as e:  # noqa: BLE001 -- report and keep going
            print(f"{key}: FAILED: {e}", file=sys.stderr)
            failures.append(key)

    write_license_md({k: len(v) for k, v in sampled_by_source.items()})
    write_sources_json(sampled_by_source)

    if failures:
        print(f"FAILED sources: {failures}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
